=== gorrantia/Esentri/src/main/java/ch/rhb/integra/mitarbeiter/psipenta/jaxb/psipenta.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.psipenta.de/WebServiceDataSchema" 
targetNamespace="http://www.psipenta.de/WebServiceDataSchema"
attributeFormDefault="qualified">
  <xsd:element name="Reply" type="reply"/>
  <xsd:complexType name="Result">
    <xsd:simpleContent>
      <xsd:extension base="xsd:string">
        <xsd:attribute name="type" use="required" type="resultType"/>
        <xsd:attribute name="code" type="xsd:string" use="optional"/>
      </xsd:extension>
    </xsd:simpleContent>
  </xsd:complexType>
    <xsd:simpleType name="resultType">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="error"/>
      <xsd:enumeration value="ok"/>
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:complexType name="reply">
    <xsd:sequence>
      <xsd:element name="Record" type="PropertyList" maxOccurs="1" minOccurs="1"/>
      <xsd:element name="Result" type="Result"/>
    </xsd:sequence>
  </xsd:complexType>
  
  <xsd:complexType name="PropertyListWithOptionalLines">
    <xsd:complexContent>
      <xsd:extension base="PropertyList">
        <xsd:sequence>
          <xsd:element name="Line" type="PropertyList" maxOccurs="unbounded" minOccurs="0">
          </xsd:element>
        </xsd:sequence>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  
    <xsd:complexType name="Property">
    <xsd:simpleContent>
      <xsd:extension base="xsd:string">
        <xsd:attribute name="name" use="required" type="xsd:string"/>
      </xsd:extension>
    </xsd:simpleContent>
  </xsd:complexType>
  <xsd:complexType name="PropertyList">
  <xsd:sequence>
    <xsd:element name="Property" type="Property" maxOccurs="unbounded" minOccurs="1"/>
  </xsd:sequence>
  <xsd:attribute name="key" type="xsd:string" use="required"/>
</xsd:complexType>
  
    <xsd:simpleType name="FieldName">
    <xsd:restriction base="xsd:string">
      <xsd:minLength value="1" />
      <xsd:maxLength value="32" />
      <xsd:pattern value="[a-zA-Z0-9_]+" />
      <xsd:whiteSpace value="collapse" />
      <xsd:pattern value="\*" />
    </xsd:restriction>
  </xsd:simpleType>
</xsd:schema>

=== gorrantia/Esentri/src/test/resources/psipenta.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:Reply xmlns:p="http://www.psipenta.de/WebServiceDataSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.psipenta.de/WebServiceDataSchema psipenta.xsd">
  <Record p:key="1001">
      <Property p:name="COMPANY">Rhb</Property>
      <Property p:name="COMPANYADDRESS">4841</Property>
      <Property p:name="DEGREE"/>
      <Property p:name="EMAILADRESS">michael.forrer@rhb.ch</Property>
      <Property p:name="EMPLOYEENO">10001</Property>
      <Property p:name="FIRSTNAME">Michael Testli vom Michi</Property>
      <Property p:name="HOMEPAGE">Techniker Test</Property>
      <Property p:name="ID">10001</Property>
      <Property p:name="INITIALS"/>
      <Property p:name="MOBILEPHONE"/>
      <Property p:name="NAMESUPPLEMENT"/>
      <Property p:name="OFFICEFAX">+41812886515</Property>
      <Property p:name="OFFICEPHONE">+41812886254</Property>
      <Property p:name="PERSON_FIRSTNAME"/>
      <Property p:name="PERSON_SURNAME"/>
      <Property p:name="POSITION"/>
      <Property p:name="PRIVATEADDRESS"/>
      <Property p:name="PRIVATEPHONE"/>
      <Property p:name="ROOM"/>
      <Property p:name="SUBSTITUTE"/>
      <Property p:name="SUBSTITUTESTATUS">0</Property>
      <Property p:name="SURNAME">Forrer Test</Property>
      <Property p:name="TITLE">System Engineer</Property>   
  </Record>
  <Result p:type="ok"/>
</p:Reply>
